CREATE ROLE catalog LOGIN PASSWORD 'catalog';
CREATE ROLE orders LOGIN PASSWORD 'orders';
CREATE ROLE payments LOGIN PASSWORD 'payments';

CREATE DATABASE catalog_db OWNER catalog;
CREATE DATABASE orders_db OWNER orders;
CREATE DATABASE payments_db OWNER payments;

REVOKE CONNECT ON DATABASE catalog_db FROM PUBLIC;
REVOKE CONNECT ON DATABASE orders_db FROM PUBLIC;
REVOKE CONNECT ON DATABASE payments_db FROM PUBLIC;

GRANT CONNECT ON DATABASE catalog_db TO catalog;
GRANT CONNECT ON DATABASE orders_db TO orders;
GRANT CONNECT ON DATABASE payments_db TO payments;
